[server]
port = 8085

[database]
# Lựa chọn hệ quản trị CSDL ưu tiên: mysql, postgresql, oracle, sqlite, sqlserver
engine = mysql

# Thông tin kết nối
host = 10.201.11.115
port = 3306
database = portfolio_db
username = portfolio_user
password = portfolio_password

# Cấu hình Pool & Option (Tương đương Hikari trong Java)
auto_reconnect = true
tcp_keep_alive = true
pool_max_lifetime = 600000
pool_keepalive_time = 300000
pool_connection_timeout = 20000

[orm]
# Định nghĩa giống cấu hình Hibernate/JPA
ddl_auto = update
show_sql = true
